@echo off
chcp 65001 >nul
cd /d c:\xampp\htdocs\nine
echo [1/8] backup-before-rewrite ブランチを作成...
git branch backup-before-rewrite
echo [2/8] 履歴のない new-main を作成...
git checkout --orphan new-main
echo [3/8] ステージングをクリア...
git rm -rf --cached .
echo [4/8] 現在のファイルを追加...
git add .
echo [5/8] コミット作成...
git commit -m "プロジェクト一式を追加（シークレット含まない版）"
echo [6/8] 古い main を削除...
git branch -D main
echo [7/8] new-main を main にリネーム...
git branch -m main
echo [8/8] リモートに force push...
git push -f origin main
echo.
echo 完了しました。
pause
